--- #YAML:1.0
name:               ODF-lpOD
version:            1.119
abstract:           An OpenDocument management interface
author:
    - Jean-Marie Gouarne <jean-marie.gouarne@online.fr>
license:            GPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Zip:    1.30
    File::Basename:  2.76
    File::Find:      1.01
    File::Slurp:     0
    File::Temp:      0.12
    File::Type:      0
    Image::Size:     0
    IO::File:        1.14
    LWP::Simple:     0
    Time::Local:     1.07
    XML::Twig:       3.34
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
